//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.14 at 07:19:59 PM GST 
//


package io.spring.guides.gs_producing_web_service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ccbcase" type="{http://spring.io/guides/gs-producing-web-service}ccbcase"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ccbcase"
})
@XmlRootElement(name = "getCcbcaseResponse")
public class GetCcbcaseResponse {

    @XmlElement(required = true)
    protected Ccbcase ccbcase;

    /**
     * Gets the value of the ccbcase property.
     * 
     * @return
     *     possible object is
     *     {@link Ccbcase }
     *     
     */
    public Ccbcase getCcbcase() {
        return ccbcase;
    }

    /**
     * Sets the value of the ccbcase property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ccbcase }
     *     
     */
    public void setCcbcase(Ccbcase value) {
        this.ccbcase = value;
    }

}
