//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.14 at 07:19:59 PM GST 
//


package io.spring.guides.gs_producing_web_service;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.spring.guides.gs_producing_web_service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.spring.guides.gs_producing_web_service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetWorkorderRequest }
     * 
     */
    public GetWorkorderRequest createGetWorkorderRequest() {
        return new GetWorkorderRequest();
    }

    /**
     * Create an instance of {@link GetWorkorderResponse }
     * 
     */
    public GetWorkorderResponse createGetWorkorderResponse() {
        return new GetWorkorderResponse();
    }

    /**
     * Create an instance of {@link Workorder }
     * 
     */
    public Workorder createWorkorder() {
        return new Workorder();
    }

    /**
     * Create an instance of {@link GetCcbcaseRequest }
     * 
     */
    public GetCcbcaseRequest createGetCcbcaseRequest() {
        return new GetCcbcaseRequest();
    }

    /**
     * Create an instance of {@link GetCcbcaseResponse }
     * 
     */
    public GetCcbcaseResponse createGetCcbcaseResponse() {
        return new GetCcbcaseResponse();
    }

    /**
     * Create an instance of {@link Ccbcase }
     * 
     */
    public Ccbcase createCcbcase() {
        return new Ccbcase();
    }

}
