//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.14 at 07:19:59 PM GST 
//


package io.spring.guides.gs_producing_web_service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for workorder complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="workorder"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="wonum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="woid" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="siteid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "workorder", propOrder = {
    "wonum",
    "woid",
    "siteid"
})
public class Workorder {

    @XmlElement(required = true)
    protected String wonum;
    protected int woid;
    @XmlElement(required = true)
    protected String siteid;

    /**
     * Gets the value of the wonum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWonum() {
        return wonum;
    }

    /**
     * Sets the value of the wonum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWonum(String value) {
        this.wonum = value;
    }

    /**
     * Gets the value of the woid property.
     * 
     */
    public int getWoid() {
        return woid;
    }

    /**
     * Sets the value of the woid property.
     * 
     */
    public void setWoid(int value) {
        this.woid = value;
    }

    /**
     * Gets the value of the siteid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiteid() {
        return siteid;
    }

    /**
     * Sets the value of the siteid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiteid(String value) {
        this.siteid = value;
    }

}
